wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 16
num_epochs:
  desc: null
  value: 5
architecture_A:
  desc: null
  value: ResNet50
architecture_B:
  desc: null
  value: CustomCNN
dataset:
  desc: null
  value: ImageFolder
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729370573
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
