_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 41
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
